# These are supported funding model platforms

github: gomzyakov
patreon: gomzyakov
ko_fi: gomzyakov
liberapay: gomzyakov
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
open_collective: # Replace with a single Open Collective username
