# Project language
language: php

# Choosing PHP versions to test
php:
  - '7.2'

# Start mysql service
services:
  - mysql

# Update composer
before-install:
  - composer self-update

# Install composer dependencies,
# Create database, schema and fixtures
# install: