# Project language
language: php

# Choosing PHP versions to test
php:
  - '7.2'

# Start mysql service
services:
  - mysql

# Commands to be run before your environment runs:
# - Install composer dependencies,
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --no-dev

# Update composer
before-install:
  - composer self-update

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer install --no-dev
  
# Install composer dependencies,
# Create database, schema and fixtures
install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS ap_en CHARACTER SET utf8 COLLATE utf8_general_ci;"
  - mysql -e "CREATE DATABASE IF NOT EXISTS ap_ru CHARACTER SET utf8 COLLATE utf8_general_ci;"
  - mysql -e "CREATE DATABASE IF NOT EXISTS ap_users CHARACTER SET utf8 COLLATE utf8_general_ci;"

after_success:
  - travis_retry php php-coveralls.phar